// Generated by scripts/ios-store/generate-models.py from frozen schema v2.
import Foundation
import RocoDomain

public struct Manifest: Codable, Equatable, Sendable {
    public let schemaVersion: Int
    public let contentVersion: String
    public let rulesVersion: String
    public let sourceRevision: String
    public let inputHashes: [String: String]
    public let generatorVersion: String
    public let minimumAppBuild: Int
    public let locale: String
    public let defaultSeason: SeasonID
    public let counts: [String: Int]
    public let files: [ContentFile]
    public let assets: [Asset]
    public let knownMissingAssets: [AssetID]
    public let idMigrations: [ManifestIdMigrationsElement]
    public let scope: ManifestScope
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["schemaVersion", "contentVersion", "rulesVersion", "sourceRevision", "inputHashes", "generatorVersion", "minimumAppBuild", "locale", "defaultSeason", "counts", "files", "assets", "knownMissingAssets", "idMigrations", "scope"])
        schemaVersion = try c.value("schemaVersion")
        try require(schemaVersion == 2, "Manifest.schemaVersion violates schema v2")
        contentVersion = try c.value("contentVersion")
        try require(contentVersion.count >= 1, "Manifest.contentVersion violates schema v2")
        rulesVersion = try c.value("rulesVersion")
        try require(rulesVersion.count >= 1, "Manifest.rulesVersion violates schema v2")
        sourceRevision = try c.value("sourceRevision")
        try require(matches(sourceRevision, "^[a-f0-9]{40}$"), "Manifest.sourceRevision violates schema v2")
        inputHashes = try c.value("inputHashes")
        try require(inputHashes.values.allSatisfy { matches($0, "^[a-f0-9]{64}$") }, "Manifest.inputHashes violates schema v2")
        generatorVersion = try c.value("generatorVersion")
        try require(generatorVersion.count >= 1, "Manifest.generatorVersion violates schema v2")
        minimumAppBuild = try c.value("minimumAppBuild")
        try require(minimumAppBuild >= 1, "Manifest.minimumAppBuild violates schema v2")
        locale = try c.value("locale")
        try require(locale == "zh-CN", "Manifest.locale violates schema v2")
        defaultSeason = try c.value("defaultSeason")
        try require(defaultSeason.rawValue >= 0, "Manifest.defaultSeason violates schema v2")
        counts = try c.value("counts")
        try require(counts.values.allSatisfy { $0 >= 0 }, "Manifest.counts violates schema v2")
        files = try c.value("files")
        assets = try c.value("assets")
        knownMissingAssets = try c.value("knownMissingAssets")
        try require(knownMissingAssets.allSatisfy { $0.rawValue.count >= 1 }, "Manifest.knownMissingAssets violates schema v2")
        idMigrations = try c.value("idMigrations")
        scope = try c.value("scope")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(schemaVersion, forKey: ContentKey("schemaVersion"))
        try c.encode(contentVersion, forKey: ContentKey("contentVersion"))
        try c.encode(rulesVersion, forKey: ContentKey("rulesVersion"))
        try c.encode(sourceRevision, forKey: ContentKey("sourceRevision"))
        try c.encode(inputHashes, forKey: ContentKey("inputHashes"))
        try c.encode(generatorVersion, forKey: ContentKey("generatorVersion"))
        try c.encode(minimumAppBuild, forKey: ContentKey("minimumAppBuild"))
        try c.encode(locale, forKey: ContentKey("locale"))
        try c.encode(defaultSeason, forKey: ContentKey("defaultSeason"))
        try c.encode(counts, forKey: ContentKey("counts"))
        try c.encode(files, forKey: ContentKey("files"))
        try c.encode(assets, forKey: ContentKey("assets"))
        try c.encode(knownMissingAssets, forKey: ContentKey("knownMissingAssets"))
        try c.encode(idMigrations, forKey: ContentKey("idMigrations"))
        try c.encode(scope, forKey: ContentKey("scope"))
    }
}

public struct ManifestScope: Codable, Equatable, Sendable {
    public let profile: String
    public let rootPetIds: [PetID]
    public let dependencyPetIds: [PetID]
    public let excludedPetIds: [PetID]
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["profile", "rootPetIds", "dependencyPetIds", "excludedPetIds"])
        profile = try c.value("profile")
        try require(profile == "eight-features-v1", "ManifestScope.profile violates schema v2")
        rootPetIds = try c.value("rootPetIds")
        try require(rootPetIds.allSatisfy { $0.rawValue >= 1 }, "ManifestScope.rootPetIds violates schema v2")
        dependencyPetIds = try c.value("dependencyPetIds")
        try require(dependencyPetIds.allSatisfy { $0.rawValue >= 1 }, "ManifestScope.dependencyPetIds violates schema v2")
        excludedPetIds = try c.value("excludedPetIds")
        try require(excludedPetIds.allSatisfy { $0.rawValue >= 1 }, "ManifestScope.excludedPetIds violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(profile, forKey: ContentKey("profile"))
        try c.encode(rootPetIds, forKey: ContentKey("rootPetIds"))
        try c.encode(dependencyPetIds, forKey: ContentKey("dependencyPetIds"))
        try c.encode(excludedPetIds, forKey: ContentKey("excludedPetIds"))
    }
}

public struct ManifestIdMigrationsElement: Codable, Equatable, Sendable {
    public let domain: String
    public let from: String
    public let to: String?
    public let reason: String
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["domain", "from", "to", "reason"])
        domain = try c.value("domain")
        try require(domain.count >= 1, "ManifestIdMigrationsElement.domain violates schema v2")
        from = try c.value("from")
        try require(from.count >= 1, "ManifestIdMigrationsElement.from violates schema v2")
        to = try c.value("to")
        if let to { try require(to.count >= 1, "ManifestIdMigrationsElement.to violates schema v2") }
        reason = try c.value("reason")
        try require(reason.count >= 1, "ManifestIdMigrationsElement.reason violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(domain, forKey: ContentKey("domain"))
        try c.encode(from, forKey: ContentKey("from"))
        try c.encode(to, forKey: ContentKey("to"))
        try c.encode(reason, forKey: ContentKey("reason"))
    }
}

public struct ContentFile: Codable, Equatable, Sendable {
    public let path: String
    public let bytes: Int
    public let sha256: String
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["path", "bytes", "sha256"])
        path = try c.value("path")
        try require(path.count >= 1, "ContentFile.path violates schema v2")
        bytes = try c.value("bytes")
        try require(bytes >= 0, "ContentFile.bytes violates schema v2")
        sha256 = try c.value("sha256")
        try require(matches(sha256, "^[a-f0-9]{64}$"), "ContentFile.sha256 violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(path, forKey: ContentKey("path"))
        try c.encode(bytes, forKey: ContentKey("bytes"))
        try c.encode(sha256, forKey: ContentKey("sha256"))
    }
}

public struct Asset: Codable, Equatable, Sendable {
    public let assetId: AssetID
    public let purpose: AssetPurpose
    public let sourcePath: String
    public let sourceSha256: String?
    public let sourceFormat: AssetSourceFormat?
    public let availability: AssetAvailability
    public let missingReason: String?
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["assetId", "purpose", "sourcePath", "sourceSha256", "sourceFormat", "availability", "missingReason"])
        assetId = try c.value("assetId")
        try require(assetId.rawValue.count >= 1, "Asset.assetId violates schema v2")
        purpose = try c.value("purpose")
        sourcePath = try c.value("sourcePath")
        try require(sourcePath.count >= 1, "Asset.sourcePath violates schema v2")
        sourceSha256 = try c.value("sourceSha256")
        if let sourceSha256 { try require(matches(sourceSha256, "^[a-f0-9]{64}$"), "Asset.sourceSha256 violates schema v2") }
        sourceFormat = try c.value("sourceFormat")
        availability = try c.value("availability")
        missingReason = try c.value("missingReason")
        if let missingReason { try require(missingReason.count >= 1, "Asset.missingReason violates schema v2") }
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(assetId, forKey: ContentKey("assetId"))
        try c.encode(purpose, forKey: ContentKey("purpose"))
        try c.encode(sourcePath, forKey: ContentKey("sourcePath"))
        try c.encode(sourceSha256, forKey: ContentKey("sourceSha256"))
        try c.encode(sourceFormat, forKey: ContentKey("sourceFormat"))
        try c.encode(availability, forKey: ContentKey("availability"))
        try c.encode(missingReason, forKey: ContentKey("missingReason"))
    }
}

public struct BattleEffect: Codable, Equatable, Sendable {
    public let effectId: EffectID
    public let petId: PetID?
    public let skillId: SkillID?
    public let kind: BattleEffectKind
    public let parameters: [String: JSONValue]
    public let rawDescription: String
    public let parseVersion: Int
    public let assumptions: [String]
    public let sourcePath: String
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["effectId", "petId", "skillId", "kind", "parameters", "rawDescription", "parseVersion", "assumptions", "sourcePath"])
        effectId = try c.value("effectId")
        try require(effectId.rawValue.count >= 1, "BattleEffect.effectId violates schema v2")
        petId = try c.value("petId")
        if let petId { try require(petId.rawValue >= 1, "BattleEffect.petId violates schema v2") }
        skillId = try c.value("skillId")
        if let skillId { try require(skillId.rawValue >= 1, "BattleEffect.skillId violates schema v2") }
        kind = try c.value("kind")
        parameters = try c.value("parameters")
        rawDescription = try c.value("rawDescription")
        parseVersion = try c.value("parseVersion")
        try require(parseVersion >= 1, "BattleEffect.parseVersion violates schema v2")
        assumptions = try c.value("assumptions")
        try require(assumptions.allSatisfy { $0.count >= 1 }, "BattleEffect.assumptions violates schema v2")
        sourcePath = try c.value("sourcePath")
        try require(sourcePath.count >= 1, "BattleEffect.sourcePath violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(effectId, forKey: ContentKey("effectId"))
        try c.encode(petId, forKey: ContentKey("petId"))
        try c.encode(skillId, forKey: ContentKey("skillId"))
        try c.encode(kind, forKey: ContentKey("kind"))
        try c.encode(parameters, forKey: ContentKey("parameters"))
        try c.encode(rawDescription, forKey: ContentKey("rawDescription"))
        try c.encode(parseVersion, forKey: ContentKey("parseVersion"))
        try c.encode(assumptions, forKey: ContentKey("assumptions"))
        try c.encode(sourcePath, forKey: ContentKey("sourcePath"))
    }
}

public struct Season: Codable, Equatable, Sendable {
    public let seasonId: SeasonID
    public let nameZh: String
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["seasonId", "nameZh"])
        seasonId = try c.value("seasonId")
        try require(seasonId.rawValue >= 0, "Season.seasonId violates schema v2")
        nameZh = try c.value("nameZh")
        try require(nameZh.count >= 1, "Season.nameZh violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(seasonId, forKey: ContentKey("seasonId"))
        try c.encode(nameZh, forKey: ContentKey("nameZh"))
    }
}

public struct MagicItem: Codable, Equatable, Sendable {
    public let magicItemId: MagicItemID
    public let nameZh: String
    public let description: String
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["magicItemId", "nameZh", "description"])
        magicItemId = try c.value("magicItemId")
        try require(magicItemId.rawValue >= 1, "MagicItem.magicItemId violates schema v2")
        nameZh = try c.value("nameZh")
        try require(nameZh.count >= 1, "MagicItem.nameZh violates schema v2")
        description = try c.value("description")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(magicItemId, forKey: ContentKey("magicItemId"))
        try c.encode(nameZh, forKey: ContentKey("nameZh"))
        try c.encode(description, forKey: ContentKey("description"))
    }
}

public struct Personality: Codable, Equatable, Sendable {
    public let personalityId: PersonalityID
    public let nameZh: String
    public let modifiers: PersonalityModifiers
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["personalityId", "nameZh", "modifiers"])
        personalityId = try c.value("personalityId")
        try require(personalityId.rawValue >= 1, "Personality.personalityId violates schema v2")
        nameZh = try c.value("nameZh")
        try require(nameZh.count >= 1, "Personality.nameZh violates schema v2")
        modifiers = try c.value("modifiers")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(personalityId, forKey: ContentKey("personalityId"))
        try c.encode(nameZh, forKey: ContentKey("nameZh"))
        try c.encode(modifiers, forKey: ContentKey("modifiers"))
    }
}

public struct PersonalityModifiers: Codable, Equatable, Sendable {
    public let hp: PersonalityModifiersHp
    public let physicalAttack: PersonalityModifiersPhysicalAttack
    public let magicalAttack: PersonalityModifiersMagicalAttack
    public let physicalDefense: PersonalityModifiersPhysicalDefense
    public let magicalDefense: PersonalityModifiersMagicalDefense
    public let speed: PersonalityModifiersSpeed
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["hp", "physicalAttack", "magicalAttack", "physicalDefense", "magicalDefense", "speed"])
        hp = try c.value("hp")
        physicalAttack = try c.value("physicalAttack")
        magicalAttack = try c.value("magicalAttack")
        physicalDefense = try c.value("physicalDefense")
        magicalDefense = try c.value("magicalDefense")
        speed = try c.value("speed")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(hp, forKey: ContentKey("hp"))
        try c.encode(physicalAttack, forKey: ContentKey("physicalAttack"))
        try c.encode(magicalAttack, forKey: ContentKey("magicalAttack"))
        try c.encode(physicalDefense, forKey: ContentKey("physicalDefense"))
        try c.encode(magicalDefense, forKey: ContentKey("magicalDefense"))
        try c.encode(speed, forKey: ContentKey("speed"))
    }
}

public struct BadgeLocation: Codable, Equatable, Sendable {
    public let locationId: BadgeLocationLocationId
    public let nameZh: String
    public let targetCount: Int
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["locationId", "nameZh", "targetCount"])
        locationId = try c.value("locationId")
        nameZh = try c.value("nameZh")
        try require(nameZh.count >= 1, "BadgeLocation.nameZh violates schema v2")
        targetCount = try c.value("targetCount")
        try require(targetCount >= 1, "BadgeLocation.targetCount violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(locationId, forKey: ContentKey("locationId"))
        try c.encode(nameZh, forKey: ContentKey("nameZh"))
        try c.encode(targetCount, forKey: ContentKey("targetCount"))
    }
}

public struct BadgeFootprint: Codable, Equatable, Sendable {
    public let footprintKey: FootprintKey
    public let petId: PetID
    public let familyKey: BadgeFamilyKey
    public let isLeader: Bool
    public let stageDepth: Int
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["footprintKey", "petId", "familyKey", "isLeader", "stageDepth"])
        footprintKey = try c.value("footprintKey")
        try require(matches(footprintKey.rawValue, "^pet:[1-9][0-9]*$"), "BadgeFootprint.footprintKey violates schema v2")
        petId = try c.value("petId")
        try require(petId.rawValue >= 1, "BadgeFootprint.petId violates schema v2")
        familyKey = try c.value("familyKey")
        try require(matches(familyKey.rawValue, "^species:[1-9][0-9]*$"), "BadgeFootprint.familyKey violates schema v2")
        isLeader = try c.value("isLeader")
        stageDepth = try c.value("stageDepth")
        try require(stageDepth >= 0, "BadgeFootprint.stageDepth violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(footprintKey, forKey: ContentKey("footprintKey"))
        try c.encode(petId, forKey: ContentKey("petId"))
        try c.encode(familyKey, forKey: ContentKey("familyKey"))
        try c.encode(isLeader, forKey: ContentKey("isLeader"))
        try c.encode(stageDepth, forKey: ContentKey("stageDepth"))
    }
}

public struct ShinySlot: Codable, Equatable, Sendable {
    public let slotId: ShinySlotID
    public let seasonId: SeasonID
    public let familyId: ShinyFamilyID
    public let targetPetId: PetID
    public let representativePetId: PetID
    public let memberPetIds: [PetID]
    public let portraitAssetId: AssetID?
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["slotId", "seasonId", "familyId", "targetPetId", "representativePetId", "memberPetIds", "portraitAssetId"])
        slotId = try c.value("slotId")
        try require(matches(slotId.rawValue, "^s[0-9]+-f[0-9]+-(e|p)[0-9]+$"), "ShinySlot.slotId violates schema v2")
        seasonId = try c.value("seasonId")
        try require(seasonId.rawValue >= 0, "ShinySlot.seasonId violates schema v2")
        familyId = try c.value("familyId")
        try require(familyId.rawValue >= 1, "ShinySlot.familyId violates schema v2")
        targetPetId = try c.value("targetPetId")
        try require(targetPetId.rawValue >= 1, "ShinySlot.targetPetId violates schema v2")
        representativePetId = try c.value("representativePetId")
        try require(representativePetId.rawValue >= 1, "ShinySlot.representativePetId violates schema v2")
        memberPetIds = try c.value("memberPetIds")
        try require(memberPetIds.allSatisfy { $0.rawValue >= 1 }, "ShinySlot.memberPetIds violates schema v2")
        portraitAssetId = try c.value("portraitAssetId")
        if let portraitAssetId { try require(portraitAssetId.rawValue.count >= 1, "ShinySlot.portraitAssetId violates schema v2") }
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(slotId, forKey: ContentKey("slotId"))
        try c.encode(seasonId, forKey: ContentKey("seasonId"))
        try c.encode(familyId, forKey: ContentKey("familyId"))
        try c.encode(targetPetId, forKey: ContentKey("targetPetId"))
        try c.encode(representativePetId, forKey: ContentKey("representativePetId"))
        try c.encode(memberPetIds, forKey: ContentKey("memberPetIds"))
        try c.encode(portraitAssetId, forKey: ContentKey("portraitAssetId"))
    }
}

public struct Family: Codable, Equatable, Sendable {
    public let kind: FamilyKind
    public let familyKey: FamilyKey
    public let representativePetId: PetID
    public let memberPetIds: [PetID]
    public let typeIds: [TypeID]
    public let ordinal: Int
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["kind", "familyKey", "representativePetId", "memberPetIds", "typeIds", "ordinal"])
        kind = try c.value("kind")
        familyKey = try c.value("familyKey")
        try require(familyKey.rawValue.count >= 1, "Family.familyKey violates schema v2")
        representativePetId = try c.value("representativePetId")
        try require(representativePetId.rawValue >= 1, "Family.representativePetId violates schema v2")
        memberPetIds = try c.value("memberPetIds")
        try require(memberPetIds.allSatisfy { $0.rawValue >= 1 }, "Family.memberPetIds violates schema v2")
        typeIds = try c.value("typeIds")
        try require(typeIds.allSatisfy { $0.rawValue >= 1 }, "Family.typeIds violates schema v2")
        ordinal = try c.value("ordinal")
        try require(ordinal >= 0, "Family.ordinal violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(kind, forKey: ContentKey("kind"))
        try c.encode(familyKey, forKey: ContentKey("familyKey"))
        try c.encode(representativePetId, forKey: ContentKey("representativePetId"))
        try c.encode(memberPetIds, forKey: ContentKey("memberPetIds"))
        try c.encode(typeIds, forKey: ContentKey("typeIds"))
        try c.encode(ordinal, forKey: ContentKey("ordinal"))
    }
}

public struct Evolution: Codable, Equatable, Sendable {
    public let edgeId: EvolutionEdgeID
    public let sourcePetId: PetID
    public let targetPetId: PetID
    public let ordinal: Int
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["edgeId", "sourcePetId", "targetPetId", "ordinal"])
        edgeId = try c.value("edgeId")
        try require(edgeId.rawValue.count >= 1, "Evolution.edgeId violates schema v2")
        sourcePetId = try c.value("sourcePetId")
        try require(sourcePetId.rawValue >= 1, "Evolution.sourcePetId violates schema v2")
        targetPetId = try c.value("targetPetId")
        try require(targetPetId.rawValue >= 1, "Evolution.targetPetId violates schema v2")
        ordinal = try c.value("ordinal")
        try require(ordinal >= 0, "Evolution.ordinal violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(edgeId, forKey: ContentKey("edgeId"))
        try c.encode(sourcePetId, forKey: ContentKey("sourcePetId"))
        try c.encode(targetPetId, forKey: ContentKey("targetPetId"))
        try c.encode(ordinal, forKey: ContentKey("ordinal"))
    }
}

public struct Trait: Codable, Equatable, Sendable {
    public let traitId: TraitID
    public let nameZh: String
    public let description: String
    public let iconAssetId: AssetID?
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["traitId", "nameZh", "description", "iconAssetId"])
        traitId = try c.value("traitId")
        try require(traitId.rawValue >= 1, "Trait.traitId violates schema v2")
        nameZh = try c.value("nameZh")
        try require(nameZh.count >= 1, "Trait.nameZh violates schema v2")
        description = try c.value("description")
        iconAssetId = try c.value("iconAssetId")
        if let iconAssetId { try require(iconAssetId.rawValue.count >= 1, "Trait.iconAssetId violates schema v2") }
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(traitId, forKey: ContentKey("traitId"))
        try c.encode(nameZh, forKey: ContentKey("nameZh"))
        try c.encode(description, forKey: ContentKey("description"))
        try c.encode(iconAssetId, forKey: ContentKey("iconAssetId"))
    }
}

public struct PetSkill: Codable, Equatable, Sendable {
    public let petId: PetID
    public let skillId: SkillID
    public let source: PetSkillSource
    public let legacyTypeId: TypeID?
    public let ordinal: Int
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["petId", "skillId", "source", "legacyTypeId", "ordinal"])
        petId = try c.value("petId")
        try require(petId.rawValue >= 1, "PetSkill.petId violates schema v2")
        skillId = try c.value("skillId")
        try require(skillId.rawValue >= 1, "PetSkill.skillId violates schema v2")
        source = try c.value("source")
        legacyTypeId = try c.value("legacyTypeId")
        if let legacyTypeId { try require(legacyTypeId.rawValue >= 1, "PetSkill.legacyTypeId violates schema v2") }
        ordinal = try c.value("ordinal")
        try require(ordinal >= 0, "PetSkill.ordinal violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(petId, forKey: ContentKey("petId"))
        try c.encode(skillId, forKey: ContentKey("skillId"))
        try c.encode(source, forKey: ContentKey("source"))
        try c.encode(legacyTypeId, forKey: ContentKey("legacyTypeId"))
        try c.encode(ordinal, forKey: ContentKey("ordinal"))
    }
}

public struct SkillGroup: Codable, Equatable, Sendable {
    public let groupId: SkillGroupID
    public let displayId: SkillID
    public let aliasIds: [SkillID]
    public let nameZh: String
    public let ordinal: Int
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["groupId", "displayId", "aliasIds", "nameZh", "ordinal"])
        groupId = try c.value("groupId")
        try require(groupId.rawValue.count >= 1, "SkillGroup.groupId violates schema v2")
        displayId = try c.value("displayId")
        try require(displayId.rawValue >= 1, "SkillGroup.displayId violates schema v2")
        aliasIds = try c.value("aliasIds")
        try require(aliasIds.allSatisfy { $0.rawValue >= 1 }, "SkillGroup.aliasIds violates schema v2")
        nameZh = try c.value("nameZh")
        try require(nameZh.count >= 1, "SkillGroup.nameZh violates schema v2")
        ordinal = try c.value("ordinal")
        try require(ordinal >= 0, "SkillGroup.ordinal violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(groupId, forKey: ContentKey("groupId"))
        try c.encode(displayId, forKey: ContentKey("displayId"))
        try c.encode(aliasIds, forKey: ContentKey("aliasIds"))
        try c.encode(nameZh, forKey: ContentKey("nameZh"))
        try c.encode(ordinal, forKey: ContentKey("ordinal"))
    }
}

public struct Skill: Codable, Equatable, Sendable {
    public let skillId: SkillID
    public let nameZh: String
    public let category: SkillCategory
    public let typeId: TypeID?
    public let power: Double?
    public let energyCost: Double?
    public let description: String
    public let iconAssetId: AssetID?
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["skillId", "nameZh", "category", "typeId", "power", "energyCost", "description", "iconAssetId"])
        skillId = try c.value("skillId")
        try require(skillId.rawValue >= 1, "Skill.skillId violates schema v2")
        nameZh = try c.value("nameZh")
        try require(nameZh.count >= 1, "Skill.nameZh violates schema v2")
        category = try c.value("category")
        typeId = try c.value("typeId")
        if let typeId { try require(typeId.rawValue >= 1, "Skill.typeId violates schema v2") }
        power = try c.value("power")
        energyCost = try c.value("energyCost")
        description = try c.value("description")
        iconAssetId = try c.value("iconAssetId")
        if let iconAssetId { try require(iconAssetId.rawValue.count >= 1, "Skill.iconAssetId violates schema v2") }
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(skillId, forKey: ContentKey("skillId"))
        try c.encode(nameZh, forKey: ContentKey("nameZh"))
        try c.encode(category, forKey: ContentKey("category"))
        try c.encode(typeId, forKey: ContentKey("typeId"))
        try c.encode(power, forKey: ContentKey("power"))
        try c.encode(energyCost, forKey: ContentKey("energyCost"))
        try c.encode(description, forKey: ContentKey("description"))
        try c.encode(iconAssetId, forKey: ContentKey("iconAssetId"))
    }
}

public struct BattleType: Codable, Equatable, Sendable {
    public let typeId: TypeID
    public let name: String
    public let nameZh: String
    public let normalBattleType: Bool
    public let weakToTypeIds: [TypeID]
    public let resistToTypeIds: [TypeID]
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["typeId", "name", "nameZh", "normalBattleType", "weakToTypeIds", "resistToTypeIds"])
        typeId = try c.value("typeId")
        try require(typeId.rawValue >= 1, "BattleType.typeId violates schema v2")
        name = try c.value("name")
        try require(name.count >= 1, "BattleType.name violates schema v2")
        nameZh = try c.value("nameZh")
        try require(nameZh.count >= 1, "BattleType.nameZh violates schema v2")
        normalBattleType = try c.value("normalBattleType")
        weakToTypeIds = try c.value("weakToTypeIds")
        try require(weakToTypeIds.allSatisfy { $0.rawValue >= 1 }, "BattleType.weakToTypeIds violates schema v2")
        resistToTypeIds = try c.value("resistToTypeIds")
        try require(resistToTypeIds.allSatisfy { $0.rawValue >= 1 }, "BattleType.resistToTypeIds violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(typeId, forKey: ContentKey("typeId"))
        try c.encode(name, forKey: ContentKey("name"))
        try c.encode(nameZh, forKey: ContentKey("nameZh"))
        try c.encode(normalBattleType, forKey: ContentKey("normalBattleType"))
        try c.encode(weakToTypeIds, forKey: ContentKey("weakToTypeIds"))
        try c.encode(resistToTypeIds, forKey: ContentKey("resistToTypeIds"))
    }
}

public struct PetDetail: Codable, Equatable, Sendable {
    public let petId: PetID
    public let traitId: TraitID?
    public let worldProfile: [String: String]?
    public let catchInfo: PetDetailCatchInfo?
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["petId", "traitId", "worldProfile", "catchInfo"])
        petId = try c.value("petId")
        try require(petId.rawValue >= 1, "PetDetail.petId violates schema v2")
        traitId = try c.value("traitId")
        if let traitId { try require(traitId.rawValue >= 1, "PetDetail.traitId violates schema v2") }
        worldProfile = try c.value("worldProfile")
        catchInfo = try c.value("catchInfo")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(petId, forKey: ContentKey("petId"))
        try c.encode(traitId, forKey: ContentKey("traitId"))
        try c.encode(worldProfile, forKey: ContentKey("worldProfile"))
        try c.encode(catchInfo, forKey: ContentKey("catchInfo"))
    }
}

public struct PetDetailCatchInfo: Codable, Equatable, Sendable {
    public let thresholdRaw: Int?
    public let guaranteeRateBasisPoints: Double?
    public let ballLevelRaw: Int?
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["thresholdRaw", "guaranteeRateBasisPoints", "ballLevelRaw"])
        thresholdRaw = try c.value("thresholdRaw")
        if let thresholdRaw { try require(thresholdRaw >= 0, "PetDetailCatchInfo.thresholdRaw violates schema v2") }
        guaranteeRateBasisPoints = try c.value("guaranteeRateBasisPoints")
        if let guaranteeRateBasisPoints { try require(guaranteeRateBasisPoints >= 0, "PetDetailCatchInfo.guaranteeRateBasisPoints violates schema v2") }
        ballLevelRaw = try c.value("ballLevelRaw")
        if let ballLevelRaw { try require(ballLevelRaw >= 0, "PetDetailCatchInfo.ballLevelRaw violates schema v2") }
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(thresholdRaw, forKey: ContentKey("thresholdRaw"))
        try c.encode(guaranteeRateBasisPoints, forKey: ContentKey("guaranteeRateBasisPoints"))
        try c.encode(ballLevelRaw, forKey: ContentKey("ballLevelRaw"))
    }
}

public struct Pet: Codable, Equatable, Sendable {
    public let petId: PetID
    public let speciesId: SpeciesID
    public let handbookId: HandbookID?
    public let nameZh: String
    public let resourceKey: String
    public let searchAliases: [String]
    public let form: String
    public let typeIds: [TypeID]
    public let defaultLegacyTypeId: TypeID?
    public let implemented: Bool
    public let publicVisible: Bool
    public let isLeader: Bool
    public let leaderPotential: Bool
    public let attackStyle: PetAttackStyle
    public let baseStats: BaseStats
    public let parentPetId: PetID?
    public let portraitAssetId: AssetID?
    public let ordinal: Int
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["petId", "speciesId", "handbookId", "nameZh", "resourceKey", "searchAliases", "form", "typeIds", "defaultLegacyTypeId", "implemented", "publicVisible", "isLeader", "leaderPotential", "attackStyle", "baseStats", "parentPetId", "portraitAssetId", "ordinal"])
        petId = try c.value("petId")
        try require(petId.rawValue >= 1, "Pet.petId violates schema v2")
        speciesId = try c.value("speciesId")
        try require(speciesId.rawValue >= 1, "Pet.speciesId violates schema v2")
        handbookId = try c.value("handbookId")
        if let handbookId { try require(handbookId.rawValue >= 1, "Pet.handbookId violates schema v2") }
        nameZh = try c.value("nameZh")
        try require(nameZh.count >= 1, "Pet.nameZh violates schema v2")
        resourceKey = try c.value("resourceKey")
        try require(resourceKey.count >= 1, "Pet.resourceKey violates schema v2")
        searchAliases = try c.value("searchAliases")
        try require(searchAliases.allSatisfy { $0.count >= 1 }, "Pet.searchAliases violates schema v2")
        form = try c.value("form")
        try require(form.count >= 1, "Pet.form violates schema v2")
        typeIds = try c.value("typeIds")
        try require(typeIds.allSatisfy { $0.rawValue >= 1 }, "Pet.typeIds violates schema v2")
        defaultLegacyTypeId = try c.value("defaultLegacyTypeId")
        if let defaultLegacyTypeId { try require(defaultLegacyTypeId.rawValue >= 1, "Pet.defaultLegacyTypeId violates schema v2") }
        implemented = try c.value("implemented")
        publicVisible = try c.value("publicVisible")
        isLeader = try c.value("isLeader")
        leaderPotential = try c.value("leaderPotential")
        attackStyle = try c.value("attackStyle")
        baseStats = try c.value("baseStats")
        parentPetId = try c.value("parentPetId")
        if let parentPetId { try require(parentPetId.rawValue >= 1, "Pet.parentPetId violates schema v2") }
        portraitAssetId = try c.value("portraitAssetId")
        if let portraitAssetId { try require(portraitAssetId.rawValue.count >= 1, "Pet.portraitAssetId violates schema v2") }
        ordinal = try c.value("ordinal")
        try require(ordinal >= 0, "Pet.ordinal violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(petId, forKey: ContentKey("petId"))
        try c.encode(speciesId, forKey: ContentKey("speciesId"))
        try c.encode(handbookId, forKey: ContentKey("handbookId"))
        try c.encode(nameZh, forKey: ContentKey("nameZh"))
        try c.encode(resourceKey, forKey: ContentKey("resourceKey"))
        try c.encode(searchAliases, forKey: ContentKey("searchAliases"))
        try c.encode(form, forKey: ContentKey("form"))
        try c.encode(typeIds, forKey: ContentKey("typeIds"))
        try c.encode(defaultLegacyTypeId, forKey: ContentKey("defaultLegacyTypeId"))
        try c.encode(implemented, forKey: ContentKey("implemented"))
        try c.encode(publicVisible, forKey: ContentKey("publicVisible"))
        try c.encode(isLeader, forKey: ContentKey("isLeader"))
        try c.encode(leaderPotential, forKey: ContentKey("leaderPotential"))
        try c.encode(attackStyle, forKey: ContentKey("attackStyle"))
        try c.encode(baseStats, forKey: ContentKey("baseStats"))
        try c.encode(parentPetId, forKey: ContentKey("parentPetId"))
        try c.encode(portraitAssetId, forKey: ContentKey("portraitAssetId"))
        try c.encode(ordinal, forKey: ContentKey("ordinal"))
    }
}

public struct BaseStats: Codable, Equatable, Sendable {
    public let hp: Int
    public let physicalAttack: Int
    public let magicalAttack: Int
    public let physicalDefense: Int
    public let magicalDefense: Int
    public let speed: Int
    public init(from decoder: any Decoder) throws {
        let c = try StrictObject(decoder, keys: ["hp", "physicalAttack", "magicalAttack", "physicalDefense", "magicalDefense", "speed"])
        hp = try c.value("hp")
        try require(hp >= 0, "BaseStats.hp violates schema v2")
        physicalAttack = try c.value("physicalAttack")
        try require(physicalAttack >= 0, "BaseStats.physicalAttack violates schema v2")
        magicalAttack = try c.value("magicalAttack")
        try require(magicalAttack >= 0, "BaseStats.magicalAttack violates schema v2")
        physicalDefense = try c.value("physicalDefense")
        try require(physicalDefense >= 0, "BaseStats.physicalDefense violates schema v2")
        magicalDefense = try c.value("magicalDefense")
        try require(magicalDefense >= 0, "BaseStats.magicalDefense violates schema v2")
        speed = try c.value("speed")
        try require(speed >= 0, "BaseStats.speed violates schema v2")
    }
    public func encode(to encoder: any Encoder) throws {
        var c = encoder.container(keyedBy: ContentKey.self)
        try c.encode(hp, forKey: ContentKey("hp"))
        try c.encode(physicalAttack, forKey: ContentKey("physicalAttack"))
        try c.encode(magicalAttack, forKey: ContentKey("magicalAttack"))
        try c.encode(physicalDefense, forKey: ContentKey("physicalDefense"))
        try c.encode(magicalDefense, forKey: ContentKey("magicalDefense"))
        try c.encode(speed, forKey: ContentKey("speed"))
    }
}

public enum AssetPurpose: String, Codable, Sendable {
    case portraitGrid = "portraitGrid"
    case skill = "skill"
    case trait = "trait"
}
public enum AssetSourceFormat: String, Codable, Sendable {
    case webp = "webp"
}
public enum AssetAvailability: String, Codable, Sendable {
    case available = "available"
    case missing = "missing"
}
public enum BattleEffectKind: String, Codable, Sendable {
    case choice = "choice"
    case instantPower = "instantPower"
    case hpThreshold = "hpThreshold"
    case swarmPower = "swarmPower"
    case swarmHits = "swarmHits"
    case burnStage = "burnStage"
    case meteorBallSpeed = "meteorBallSpeed"
    case unsupported = "unsupported"
}
public enum PersonalityModifiersHp: Double, Codable, Sendable {
    case decreased = -0.1
    case neutral = 0
    case increased = 0.2
}
public enum PersonalityModifiersPhysicalAttack: Double, Codable, Sendable {
    case decreased = -0.1
    case neutral = 0
    case increased = 0.2
}
public enum PersonalityModifiersMagicalAttack: Double, Codable, Sendable {
    case decreased = -0.1
    case neutral = 0
    case increased = 0.2
}
public enum PersonalityModifiersPhysicalDefense: Double, Codable, Sendable {
    case decreased = -0.1
    case neutral = 0
    case increased = 0.2
}
public enum PersonalityModifiersMagicalDefense: Double, Codable, Sendable {
    case decreased = -0.1
    case neutral = 0
    case increased = 0.2
}
public enum PersonalityModifiersSpeed: Double, Codable, Sendable {
    case decreased = -0.1
    case neutral = 0
    case increased = 0.2
}
public enum BadgeLocationLocationId: String, Codable, Sendable {
    case somia = "somia"
    case stonehenge = "stonehenge"
    case plata = "plata"
}
public enum FamilyKind: String, Codable, Sendable {
    case badgeRoot = "badgeRoot"
    case skillTerminal = "skillTerminal"
}
public enum PetSkillSource: String, Codable, Sendable {
    case pool = "pool"
    case stone = "stone"
    case bloodline = "bloodline"
}
public enum SkillCategory: String, Codable, Sendable {
    case physicalAttack = "Physical Attack"
    case magicAttack = "Magic Attack"
    case status = "Status"
    case defense = "Defense"
    case unknown = "Unknown"
}
public enum PetAttackStyle: String, Codable, Sendable {
    case physical = "Physical"
    case magic = "Magic"
    case both = "Both"
    case unknown = "Unknown"
}
