"""Generate strict, immutable Codable DTOs from the frozen v2 schema. No data writes."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[2]
schema = json.loads((root / 'shared/content/content.schema.json').read_text())
defs = schema['$defs']
objects = {k: v for k, v in defs.items() if v.get('type') == 'object'}
extra = {}
overrides = {'Manifest.defaultSeason': 'SeasonID', 'Season.seasonId': 'SeasonID', 'ShinySlot.seasonId': 'SeasonID', 'ShinySlot.familyId': 'ShinyFamilyID', 'SkillGroup.displayId': 'SkillID', 'SkillGroup.aliasIds': '[SkillID]', 'MagicItem.magicItemId': 'MagicItemID', 'Family.familyKey': 'FamilyKey', 'BadgeFootprint.footprintKey': 'FootprintKey', 'BattleEffect.effectId': 'EffectID'}
enums = {}
def type_for(s, name):
    if name in overrides: return overrides[name]
    if '$ref' in s: return s['$ref'].split('/')[-1]
    if 'anyOf' in s:
        return type_for(next(x for x in s['anyOf'] if x.get('type') != 'null'), name) + '?'
    if 'enum' in s:
        vals = [x for x in s['enum'] if x is not None]
        ename = ''.join(x[:1].upper() + x[1:] for x in name.split('.'))
        enums[ename] = vals
        return ename + ('?' if None in s['enum'] else '')
    if 'const' in s: return 'Int' if isinstance(s['const'], int) else 'String'
    t = s['type']
    if t == 'array': return '[' + type_for(s['items'], name + 'Element') + ']'
    if t == 'object':
        if 'properties' in s:
            ename = ''.join(x[:1].upper() + x[1:] for x in name.split('.'))
            extra[ename] = s
            return ename
        return '[String: ' + (type_for(s['additionalProperties'], name+'Value') if isinstance(s.get('additionalProperties'), dict) else 'JSONValue') + ']'
    return {'integer':'Int','number':'Double','string':'String','boolean':'Bool'}[t]

def conditions(s, expr, typ):
    if '$ref' in s:
        ref = s['$ref'].split('/')[-1]
        if defs[ref].get('type') != 'object': return conditions(defs[ref], expr+'.rawValue', 'Int' if defs[ref].get('type') == 'integer' else 'String')
        return []
    if 'anyOf' in s: return conditions(next(x for x in s['anyOf'] if x.get('type') != 'null'),expr,typ)
    # Overrides to nominal IDs; their raw values retain the schema constraints.
    if typ not in ['Int','Double','String','Bool'] and not typ.startswith('[') and s.get('type') in ['integer','string']:
        expr += '.rawValue'
    checks = []
    if 'minimum' in s: checks.append(f'{expr} >= {s["minimum"]}')
    if 'minLength' in s: checks.append(f'{expr}.count >= {s["minLength"]}')
    if 'pattern' in s: checks.append(f'matches({expr}, {json.dumps(s["pattern"])})')
    if 'const' in s: checks.append(f'{expr} == {json.dumps(s["const"])}')
    if s.get('type') == 'array':
        sub = conditions(s['items'], '$0', typ[1:-1])
        if sub: checks.append(f'{expr}.allSatisfy {{ '+ ' && '.join(sub)+' }')
    if isinstance(s.get('additionalProperties'),dict):
        sub = conditions(s['additionalProperties'],'$0', 'String')
        if sub: checks.append(f'{expr}.values.allSatisfy {{ '+' && '.join(sub)+' }')
    return checks

structs = []
while objects:
    name, s = objects.popitem()
    props = [(key, val, type_for(val, name+'.'+key)) for key,val in s['properties'].items()]
    lines = [f'public struct {name}: Codable, Equatable, Sendable {{']
    lines += [f'    public let {key}: {typ}' for key,val,typ in props]
    lines += ['    public init(from decoder: any Decoder) throws {', '        let c = try StrictObject(decoder, keys: '+json.dumps(list(s['properties']))+')']
    for key,val,typ in props:
        lines += [f'        {key} = try c.value("{key}")']
        optional = typ.endswith('?')
        cond = conditions(val,key,typ.rstrip('?'))
        if cond:
            stmt = f'try require('+ ' && '.join(cond) + f', "{name}.{key} violates schema v2")'
            lines += [f'        if let {key} {{ {stmt} }}' if optional else '        '+stmt]
    lines += ['    }', '    public func encode(to encoder: any Encoder) throws {', '        var c = encoder.container(keyedBy: ContentKey.self)']
    lines += [f'        try c.encode({key}, forKey: ContentKey("{key}"))' for key, val, typ in props]
    lines += ['    }','}']
    structs.append('\n'.join(lines))
    objects.update(extra); extra.clear()

enumlines=[]
for name,vals in enums.items():
    raw = 'String' if isinstance(vals[0],str) else 'Double'
    enumlines.append(f'public enum {name}: {raw}, Codable, Sendable {{')
    for i,v in enumerate(vals):
        case = ''.join(word[:1].lower()+word[1:] if j==0 else word[:1].upper()+word[1:] for j,word in enumerate(v.split())) if isinstance(v,str) else ['decreased','neutral','increased'][i]
        enumlines.append(f'    case {case} = {json.dumps(v)}')
    enumlines.append('}')
out = '// Generated by scripts/ios-store/generate-models.py from frozen schema v2.\nimport Foundation\nimport RocoDomain\n\n'+'\n\n'.join(structs)+'\n\n'+'\n'.join(enumlines)+'\n'
(root/'ios/Packages/RocoContent/Sources/RocoContent/ContentModels.swift').write_text(out)
