/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/attributes': RouteRecordInfo<
      '/attributes',
      '/attributes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/breeding': RouteRecordInfo<
      '/breeding',
      '/breeding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/egggroup': RouteRecordInfo<
      '/egggroup',
      '/egggroup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/encyclopedia': RouteRecordInfo<
      '/encyclopedia',
      '/encyclopedia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/handbook-progress': RouteRecordInfo<
      '/handbook-progress',
      '/handbook-progress',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/incubate': RouteRecordInfo<
      '/incubate',
      '/incubate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/items': RouteRecordInfo<
      '/items',
      '/items',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pets/[id]': RouteRecordInfo<
      '/pets/[id]',
      '/pets/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/pvp': RouteRecordInfo<
      '/pvp',
      '/pvp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/skills': RouteRecordInfo<
      '/skills',
      '/skills',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/table': RouteRecordInfo<
      '/table',
      '/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/team': RouteRecordInfo<
      '/team',
      '/team',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/attributes.vue': {
      routes:
        | '/attributes'
      views:
        | never
    }
    'src/pages/breeding.vue': {
      routes:
        | '/breeding'
      views:
        | never
    }
    'src/pages/egggroup.vue': {
      routes:
        | '/egggroup'
      views:
        | never
    }
    'src/pages/encyclopedia.vue': {
      routes:
        | '/encyclopedia'
      views:
        | never
    }
    'src/pages/handbook-progress.vue': {
      routes:
        | '/handbook-progress'
      views:
        | never
    }
    'src/pages/incubate.vue': {
      routes:
        | '/incubate'
      views:
        | never
    }
    'src/pages/items.vue': {
      routes:
        | '/items'
      views:
        | never
    }
    'src/pages/pets/[id].vue': {
      routes:
        | '/pets/[id]'
      views:
        | never
    }
    'src/pages/pvp.vue': {
      routes:
        | '/pvp'
      views:
        | never
    }
    'src/pages/skills.vue': {
      routes:
        | '/skills'
      views:
        | never
    }
    'src/pages/table.vue': {
      routes:
        | '/table'
      views:
        | never
    }
    'src/pages/team.vue': {
      routes:
        | '/team'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
